CMDB-master/assets/urls.py
from django.urls import path
from assets import views


app_name = 'assets'


urlpatterns = [
    path('report/', views.report, name='report'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('index/', views.index, name='index'),
    path('detail/<int:asset_id>/', views.detail, name='detail'),
    path('', views.dashboard),
]

CMDB/urls.py
import django.shortcuts
from django.contrib import admin
from django.urls import path
from django.urls import include
from login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login),
    path('assets/', include('assets.urls')),
    path('register/', views.register),
    path('logout/', views.logout, name='logout'),
    path('captcha/', include('captcha.urls')),
    path('confirm/', views.user_confirm),
    path('', lambda x: django.shortcuts.redirect('/login/'))
]

assets/urls.py
from django.urls import path
from assets import views


app_name = 'assets'


urlpatterns = [
    path('report/', views.report, name='report'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('index/', views.index, name='index'),
    path('sales_predictions/', views.sales_predictions, name='sales_predictions'),
    path('sales_ranking/', views.sales_ranking, name='sales_ranking'),
    path('rating_ranking/', views.rating_ranking, name='rating_ranking'),
    path('detail/<int:asset_id>/', views.detail, name='detail'),
    path('', views.dashboard),
]

CMDB-master/assets/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
import json
from assets import models
from assets import asset_handler
from django.shortcuts import get_object_or_404


def index(request):
    """
    资产总表视图
    :param request:
    :return:
    """
    assets = models.CarDetail.objects.all()
    return render(request, 'assets/index.html', locals())

def logout(request):
    if not request.session.get('is_login', None):
        return redirect('/login/')

    request.session.flush()
    # del request.session['is_login']
    return redirect("/login/")

def dashboard(request):

    total = 974.4215
    upline = 400.6933
    offline = 37.5937
    breakdown = 49.1433
    backup = 80.9644
    unknown = 403.0268

    up_rate = round(upline/total*100)
    o_rate = round(offline / total * 100)
    un_rate = round(unknown / total * 100)
    bd_rate = round(breakdown / total * 100)
    bu_rate = round(backup / total * 100)

    server_number = 400.6933
    networkdevice_number = 37.5937
    storagedevice_number = 49.1433
    securitydevice_number = 80.9644
    software_number = 403.0268

    data_point1 = 707.8011
    data_point2 = 67.4509
    data_point3 = 549.4174
    data_point4 = 511.4561
    data_point5 = 517.2504
    data_point6 = 400.6933
    data_point7 = 525.7368529917002
    data_point8 = 28.5909
    data_point9 = 18.0632
    data_point10 = 27.5841
    data_point11 = 86.2701
    data_point12 = 106.9909
    data_point13 = 37.5937
    data_point14 = 52.367530994445086
    data_point15 = 93.6271
    data_point16 = 77.7454
    data_point17 = 49.3141
    data_point18 = 59.7801
    data_point19 = 58.6122
    data_point20 = 49.1433
    data_point21 = 40.359322853408754
    data_point22 = 65.5337
    data_point23 = 65.8892
    data_point24 = 67.9619
    data_point25 = 67.4328
    data_point26 = 92.3904
    data_point27 = 80.9644
    data_point28 = 80.22391111564636
    data_point29 = 28.1050
    data_point30 = 62.1570
    data_point31 = 103.9451
    data_point32 = 282.5171
    data_point33 = 535.9235
    data_point34 = 403.0268
    data_point35 = 1268.8171115173817

    return render(request, 'assets/dashboard.html', locals())


def detail(request, asset_id):
    """
    以显示服务器类型资产详细为例，安全设备、存储设备、网络设备等参照此例。
    :param request:
    :param asset_id:
    :return:
    """

    asset = get_object_or_404(models.CarDetail, id=asset_id)
    inform = get_object_or_404(models.CarInfo, id=asset_id-1)
    return render(request, 'assets/detail.html', locals())





@csrf_exempt
def report(request):
    if request.method == 'POST':
        asset_data = request.POST.get('asset_data')
        data = json.loads(asset_data)
        if not data:
            return HttpResponse('没有数据！')
        if not issubclass(dict, type(data)):
            return HttpResponse('数据必须为字典格式！')
        # 你的检测代码

        sn = data.get('sn', None)

        if sn:
            asset_obj = models.Asset.objects.filter(sn=sn)  # [obj]
            if asset_obj:
                update_asset = asset_handler.UpdateAsset(request, asset_obj[0], data)
                return HttpResponse('资产数据已经更新。')
            else:
                obj = asset_handler.NewAsset(request, data)
                response = obj.add_to_new_assets_zone()
                return HttpResponse(response)
        else:
            return HttpResponse('没有资产sn，请检查数据内容！')

    return HttpResponse('200 ok')

assets/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.views.decorators.csrf import csrf_exempt
# Create your views here.
import json
from assets import models
from assets import asset_handler
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect


def index(request):
    """
    资产总表视图
    :param request:
    :return:
    """
    assets = models.CarDetail.objects.all()
    return render(request, 'assets/index.html', locals())


def logout(request):
    if not request.session.get('is_login', None):
        return redirect('/login/')

    request.session.flush()
    # del request.session['is_login']
    return redirect("/login/")


def dashboard(request):
    total = 974.4215
    upline = 400.6933
    offline = 37.5937
    breakdown = 49.1433
    backup = 80.9644
    unknown = 403.0268

    up_rate = round(upline / total * 100)
    o_rate = round(offline / total * 100)
    un_rate = round(unknown / total * 100)
    bd_rate = round(breakdown / total * 100)
    bu_rate = round(backup / total * 100)

    server_number = 400.6933
    networkdevice_number = 37.5937
    storagedevice_number = 49.1433
    securitydevice_number = 80.9644
    software_number = 403.0268

    data_point1 = 707.8011
    data_point2 = 67.4509
    data_point3 = 549.4174
    data_point4 = 511.4561
    data_point5 = 517.2504
    data_point6 = 400.6933
    data_point7 = 525.7368529917002
    data_point8 = 28.5909
    data_point9 = 18.0632
    data_point10 = 27.5841
    data_point11 = 86.2701
    data_point12 = 106.9909
    data_point13 = 37.5937
    data_point14 = 52.367530994445086
    data_point15 = 93.6271
    data_point16 = 77.7454
    data_point17 = 49.3141
    data_point18 = 59.7801
    data_point19 = 58.6122
    data_point20 = 49.1433
    data_point21 = 40.359322853408754
    data_point22 = 65.5337
    data_point23 = 65.8892
    data_point24 = 67.9619
    data_point25 = 67.4328
    data_point26 = 92.3904
    data_point27 = 80.9644
    data_point28 = 80.22391111564636
    data_point29 = 28.1050
    data_point30 = 62.1570
    data_point31 = 103.9451
    data_point32 = 282.5171
    data_point33 = 535.9235
    data_point34 = 403.0268
    data_point35 = 1268.8171115173817

    return render(request, 'assets/dashboard.html', locals())

# def sales_predictions(request):
#     type_point1 =
#     type_point2 =
#     type_point3 =
#     type_point4 =
#     type_point5 =
#     type_point6 =
#     type_point7 =
#     type_point8 =
#     type_point9 =
#     type_point10 =
#     type_point11 =
#     type_point12 =
#     type_point13 =
#     type_point14 =
#     type_point15 =
#     type_point16 =
#     type_point17 =
#     type_point18 =
#     type_point19 =

def rating_ranking(request):
    """
    评分排行
    """
    return render(request,'assets/rating_ranking.html', locals())

def sales_ranking(request):
    """
    销量排行
    """
    assets = models.Salesrank.objects.all()
    return render(request, 'assets/sales_ranking.html', locals())

def sales_predictions(request):
    """
    销量预测
    """
    return render(request,'assets/sales_predictions.html', locals())

def detail(request, asset_id):
    """
    以显示服务器类型资产详细为例，安全设备、存储设备、网络设备等参照此例。
    :param request:
    :param asset_id:
    :return:
    """

    asset = get_object_or_404(models.CarDetail, id=asset_id)
    inform = get_object_or_404(models.CarInfo, id=asset_id - 1)
    return render(request, 'assets/detail.html', locals())


@csrf_exempt
def report(request):
    if request.method == 'POST':
        asset_data = request.POST.get('asset_data')
        data = json.loads(asset_data)
        if not data:
            return HttpResponse('没有数据！')
        if not issubclass(dict, type(data)):
            return HttpResponse('数据必须为字典格式！')
        # 你的检测代码

        sn = data.get('sn', None)

        if sn:
            asset_obj = models.Asset.objects.filter(sn=sn)  # [obj]
            if asset_obj:
                update_asset = asset_handler.UpdateAsset(request, asset_obj[0], data)
                return HttpResponse('资产数据已经更新。')
            else:
                obj = asset_handler.NewAsset(request, data)
                response = obj.add_to_new_assets_zone()
                return HttpResponse(response)
        else:
            return HttpResponse('没有资产sn，请检查数据内容！')

    return HttpResponse('200 ok')

assets/templates/assets/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}车辆详情{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        车辆详情
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li>车辆预览</li>车辆详情</li>
      </ol>
    </section>
{% endblock %}

{% block content %}

     <!-- Main content -->
    <section class="content">
      <!-- Default box -->
      <div class="box">

        <div class="box-header with-border">
            <h3 class="box-title"><strong class="btn btn-block btn-primary btn-lg">品牌：{{ asset.brand }}</strong></h3>

            <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
              <i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
              <i class="fa fa-times"></i></button>
            </div>
        </div>

        <div class="box-body">

            <h4><b>概览:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid deepskyblue;border-bottom:1px solid deepskyblue;border-right:3px solid deepskyblue;border-top: solid deepskyblue" >
                <thead>
                <tr>
                    <th>品牌</th>
                    <th>类型</th>
                    <th>价格</th>
                    <th>销量</th>
                    <th>更新日期</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ asset.brand }}</a></td>

                    <td>{{ asset.type}}</td>

                    <td>{{ asset.price|default_if_none:"-" }}</td>

                    <td>{{ asset.sales|default_if_none:"-" }}</td>
                    <td>{{ asset.update_date|date:"Y/m/d" }}</td>
                </tr>
                </tbody>
            </table>
            <br />

            <h4><b>基本参数:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid green;border-bottom:1px solid green">
                <thead>
                    <tr>
                        <th>级别</th>
                        <th>长*宽*高(mm)</th>
                        <th>最高车速(km/h)</th>
                        <th>整车质保</th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ inform.level|default_if_none:"-" }}</td>
                    <td>{{ inform.volume|default_if_none:"-" }}</td>
                    <td>{{ inform.speed|default_if_none:"-" }}</td>
                    <td>{{ inform.protect|default_if_none:"-" }}</td>
                </tr>
                </tbody>
            </table>

            <h4><b>车身:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid deepskyblue;border-bottom:1px solid deepskyblue">
                <thead>
                <tr>
                    <th>长度</th>
                    <th>宽度</th>
                    <th>高度</th>
                    <th>轴距</th>
                    <th>前轮距</th>
                    <th>后轮距</th>
                    <th>整备质量</th>
                    <th>车身结构</th>
                    <th>车门数</th>
                    <th>座位数</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>{{ inform.length|default_if_none:"-" }}</td>
                    <td>{{ inform.width|default_if_none:"-" }}</td>
                    <td>{{ inform.height|default_if_none:"-" }}</td>
                    <td>{{ inform.wheelbase|default_if_none:"-" }}</td>
                    <td>{{ inform.front_track|default_if_none:"-" }}</td>
                    <td>{{ inform.rear_wheelbase|default_if_none:"-" }}</td>
                    <td>{{ inform.weight|default_if_none:"-" }}</td>
                    <td>{{ inform.level|default_if_none:"-" }}</td>
                    <td>{{ inform.doors|default_if_none:"-" }}</td>
                    <td>{{ inform.seats|default_if_none:"-" }}</td>
                </tr>
                </tbody>
            </table>

            <h4><b>发动机:</b></h4>
            <table border="1" class="table  table-responsive" style="border-left:3px solid orangered;border-bottom:1px solid orangered">
                <thead>
                    <tr>
                        <th>最大功率</th>
                        <th>最大扭矩</th>
                        <th>燃料形式</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ inform.power|default_if_none:"-" }}</td>
                        <td>{{ inform.torque|default_if_none:"-" }}</td>
                        <td>{{ inform.fuel|default_if_none:"-" }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->



        <div class="box-footer">
          <i class="fa fa-angle-double-left"></i>&nbsp;&nbsp;<a href="{% url 'assets:index' %}"><strong>返回资产列表页</strong></a>
        </div>
        <!-- /.box-footer-->
      </div>
      <!-- /.box -->

    </section>
    <!-- /.content -->


{% endblock %}

{% block script %}

{% endblock %}

assets/templates/assets/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}车辆预览{% endblock %}

{% block css %}
     <link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        车辆预览
        <small>Cars List</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="/dashboard.html"><i class="fa fa-dashboard"></i> 主页</a></li>
        <li class="active">车辆预览</li>
      </ol>
    </section>
{% endblock %}

{% block content %}

   <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-xs-12">

        <div class="box">
        <div class="box-header">
          <h3 class="box-title">车辆预览</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">

            <table id="assets_table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>序号</th>
                        <th>品牌</th>
                        <th>类型</th>
                        <th>价格</th>
                        <th>销量</th>
                        <th>更新日期</th>
                    </tr>
                </thead>
                <tbody>

                {% for asset in assets %}

                    <tr>
                        <td>{{ forloop.counter }}</td>

                        <td><a href="{% url 'assets:detail' asset.id %}">{{ asset.brand }}</a></td>

                        <td>{{ asset.type}}</td>

                        <td>{{ asset.price|default_if_none:"-" }}</td>

                        <td>{{ asset.sales|default_if_none:"-" }}</td>
                        <td>{{ asset.update_date|date:"Y/m/d" }}</td>
                    </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
        </div>
    <!-- /.col -->
      </div>
    <!-- /.row -->
    </section>

{% endblock %}

{% block script %}

<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminlet-2.4.10/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'adminlet-2.4.10/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'adminlet-2.4.10/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'adminlet-2.4.10/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/plugins/jqvmap/maps/jquery.vmap.world.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'adminlet-2.4.10/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'adminlet-2.4.10/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'adminlet-2.4.10/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'adminlet-2.4.10/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'adminlet-2.4.10/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlet-2.4.10/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'adminlet-2.4.10/dist/js/pages/dashboard.js' %}"></script>
<script>

$(function () {
        $('#assets_table').DataTable({
          "paging": true,       <!-- 允许分页 -->
          "lengthChange": true, <!-- 允许改变每页显示的行数 -->
          "searching": true,    <!-- 允许内容搜索 -->
          "ordering": true,     <!-- 允许排序 -->
          "info": true,         <!-- 显示信息 -->
          "autoWidth": false    <!-- 固定宽度 -->
        });
      });

</script>

{% endblock %}

assets/templates/assets/rating_ranking.html
{% extends 'base.html' %}
{% load static %}
{% block title %}评分排行{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    评分排行
    <small>Sales ranking</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> 主页</a></li>
    <li class="active">评分排行</li>
  </ol>
</section>
{% endblock %}

{% block content %}

<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">

      <div class="box">
        <div class="box-header">
          <h3 class="box-title">评分排行</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">

          <table id="assets_table" class="table table-bordered table-striped">
            <thead>
            <tr>
              <th>序号</th>
              <th>类型</th>
              <th>价格</th>
              <th>品牌</th>
              <th>评分</th>
            </tr>
            </thead>
            <tbody>

            <tr>
              <td>1</td>
              <td>幻影</td>
              <td>847.00-986.00万</td>
              <td>劳斯莱斯</td>
              <td>4.71</td>
            </tr>
            <tr>
              <td>2</td>
              <td>古思特</td>
              <td>503.00-577.00万</td>
              <td>劳斯莱斯</td>
              <td>4.70</td>
            </tr>
            <tr>
              <td>3</td>
              <td>库里南</td>
              <td>691.00-745.00万</td>
              <td>劳斯莱斯</td>
              <td>4.67</td>
            </tr>
            <tr>
              <td>4</td>
              <td>飞驰</td>
              <td>691.00-745.00万</td>
              <td>宾利</td>
              <td>4.52</td>
            </tr>
            <tr>
              <td>5</td>
              <td>添越</td>
              <td>275.50-411.20万</td>
              <td>宾利</td>
              <td>4.46</td>
            </tr>
            <tr>
              <td>6</td>
              <td>迈巴赫S级</td>
              <td>275.50-411.20万</td>
              <td>梅赛德斯-迈巴赫</td>
              <td>4.43</td>
            </tr>
            <tr>
              <td>7</td>
              <td>迈巴赫GLS</td>
              <td>183.30-312.10万</td>
              <td>梅赛德斯-迈巴赫</td>
              <td>4.40</td>
            </tr>
            <tr>
              <td>8</td>
              <td>Urus</td>
              <td>294.11-329.73万</td>
              <td>兰博基尼</td>
              <td>4.39</td>
            </tr>
            <tr>
              <td>9</td>
              <td>奥迪S8</td>
              <td>294.11-329.73万</td>
              <td>奥迪</td>
              <td>4.39</td>
            </tr>
            <tr>
              <td>10</td>
              <td>揽胜</td>
              <td>142.80-335.80万</td>
              <td>路虎</td>
              <td>4.38</td>
            </tr>

            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>

{% endblock %}

{% block script %}

<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminlet-2.4.10/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'adminlet-2.4.10/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'adminlet-2.4.10/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'adminlet-2.4.10/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/plugins/jqvmap/maps/jquery.vmap.world.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'adminlet-2.4.10/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'adminlet-2.4.10/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'adminlet-2.4.10/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'adminlet-2.4.10/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'adminlet-2.4.10/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'adminlet-2.4.10/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminlet-2.4.10/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'adminlet-2.4.10/dist/js/pages/dashboard.js' %}"></script>
<script>

  $(function () {
    $('#assets_table').DataTable({
      "paging": true,       <!-- 允许分页 -->
      "lengthChange": true, <!-- 允许改变每页显示的行数 -->
      "searching": true,    <!-- 允许内容搜索 -->
      "ordering": true,     <!-- 允许排序 -->
      "info": true,         <!-- 显示信息 -->
      "autoWidth": false    <!-- 固定宽度 -->
    });
  });

</script>

{% endblock %}